// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Cucumba.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PizzeriaFeature : object, Xunit.IClassFixture<PizzeriaFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Pizza.feature"
#line hidden
        
        public PizzeriaFeature(PizzeriaFeature.FixtureData fixtureData, Cucumba_Specs_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ro"), "Features", "Pizzeria", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Creare de pizza")]
        [Xunit.TraitAttribute("FeatureTitle", "Pizzeria")]
        [Xunit.TraitAttribute("Description", "Creare de pizza")]
        public void CreareDePizza()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creare de pizza", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
    testRunner.Given("un creator de pizza", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Date fiind ");
#line hidden
#line 6
    testRunner.And("pun blat pufos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Si ");
#line hidden
#line 7
    testRunner.And("pun sos de rosii", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Si ");
#line hidden
#line 8
    testRunner.And("pun ananas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Si ");
#line hidden
#line 9
    testRunner.And("pun peperoni", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Si ");
#line hidden
#line 10
    testRunner.And("pun ceapa", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Si ");
#line hidden
#line 11
    testRunner.When("o bag la cuptor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Cand ");
#line hidden
#line 12
    testRunner.Then("obtin o pizza", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Atunci ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PizzeriaFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PizzeriaFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
